### ISSUE TITLE
Wrong Super call?

### ISSUE THREAD

**Issue by Freddyilha** [codescv/nesgym#1]
Not sure if i'm doing something wrong or the Super call on the "model.py" line 67 that super call is the python3 syntax.
![screenshot from 2017-11-07 15-09-29](https://user-images.githubusercontent.com/5214640/32507998-131b7f34-c3d0-11e7-96ed-e9077f1e6dfb.png)

**Comment by codescv** [comment]
Yes this package is designed to run under python 3, preferably 3.4+.
